### 1 Read the Colleges dataset and clean all the attributes.

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("Top 100 Private Colleges.2003.csv")

In [3]:
data.head()

,Overall Rank,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Non-Need-Based Aid+,Average Debt,Cost Rank
0,1.0,California Institute of Technology,CA,939.0,21%,99/100%,3.0,71%,85%,10.0,"$32,682","$10,981",100%,93%,"$18,553",15%,"$10,244",4.0
1,2.0,Rice University,TX,2787.0,24%,89/92%,5.0,68%,89%,19.0,"$28,350","$14,779",100%,88%,"$22,418",34%,"$12,705",5.0
2,3.0,Williams College,MA,1985.0,23%,93/93%,8.0,89%,94%,1.0,"$36,550","$14,737",100%,89%,"$33,251",NaN,"$12,316",26.0
3,4.0,Swarthmore College,PA,1479.0,24%,94/98%,8.0,86%,92%,4.0,"$38,676","$17,386",100%,85%,"$11,404",2%,"$12,759",21.0
4,5.0,Amherst College,MA,1618.0,18%,94/92%,9.0,84%,94%,5.0,"$38,492","$14,453",100%,92%,"$33,411",NaN,"$11,544",38.0

In [7]:
data.drop(['Non-Need-Based Aid+'], axis = 1, inplace = True)

In [8]:
data.head()

,Overall Rank,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Average Debt,Cost Rank
0,1.0,California Institute of Technology,CA,939.0,21%,99/100%,3.0,71%,85%,10.0,"$32,682","$10,981",100%,93%,"$18,553","$10,244",4.0
1,2.0,Rice University,TX,2787.0,24%,89/92%,5.0,68%,89%,19.0,"$28,350","$14,779",100%,88%,"$22,418","$12,705",5.0
2,3.0,Williams College,MA,1985.0,23%,93/93%,8.0,89%,94%,1.0,"$36,550","$14,737",100%,89%,"$33,251","$12,316",26.0
3,4.0,Swarthmore College,PA,1479.0,24%,94/98%,8.0,86%,92%,4.0,"$38,676","$17,386",100%,85%,"$11,404","$12,759",21.0
4,5.0,Amherst College,MA,1618.0,18%,94/92%,9.0,84%,94%,5.0,"$38,492","$14,453",100%,92%,"$33,411","$11,544",38.0

In [5]:
data.set_index('Overall Rank', inplace = True)
data.head()

,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Non-Need-Based Aid+,Average Debt,Cost Rank
Overall Rank,,,,,,,,,,,,,,,,,
1.0,California Institute of Technology,CA,939.0,21%,99/100%,3.0,71%,85%,10.0,"$32,682","$10,981",100%,93%,"$18,553",15%,"$10,244",4.0
2.0,Rice University,TX,2787.0,24%,89/92%,5.0,68%,89%,19.0,"$28,350","$14,779",100%,88%,"$22,418",34%,"$12,705",5.0
3.0,Williams College,MA,1985.0,23%,93/93%,8.0,89%,94%,1.0,"$36,550","$14,737",100%,89%,"$33,251",NaN,"$12,316",26.0
4.0,Swarthmore College,PA,1479.0,24%,94/98%,8.0,86%,92%,4.0,"$38,676","$17,386",100%,85%,"$11,404",2%,"$12,759",21.0
5.0,Amherst College,MA,1618.0,18%,94/92%,9.0,84%,94%,5.0,"$38,492","$14,453",100%,92%,"$33,411",NaN,"$11,544",38.0

### Question 2. From all marks based attributes, remove % sign from different attributes. In SAT/ACT, Keep higher value.

In [7]:
#defining Sat converter
def satconverter(x):
    # removing % from  *SAT or ACT
    x = str(x)
    if not '/' in x:
         return np.nan
    else:
        return max(float(x.split('/')[0].replace("*","")),float(x.split('/')[1].replace("%", "").replace("*","")))

In [8]:
#printing the data
data["*SAT or ACT"]= data["*SAT or ACT"].apply(satconverter)
data.head(25)

,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Non-Need-Based Aid+,Average Debt,Cost Rank
Overall Rank,,,,,,,,,,,,,,,,,
1.0,California Institute of Technology,CA,939.0,21%,100.0,3.0,71%,85%,10.0,"$32,682","$10,981",100%,93%,"$18,553",15%,"$10,244",4.0
2.0,Rice University,TX,2787.0,24%,92.0,5.0,68%,89%,19.0,"$28,350","$14,779",100%,88%,"$22,418",34%,"$12,705",5.0
3.0,Williams College,MA,1985.0,23%,93.0,8.0,89%,94%,1.0,"$36,550","$14,737",100%,89%,"$33,251",NaN,"$12,316",26.0
4.0,Swarthmore College,PA,1479.0,24%,98.0,8.0,86%,92%,4.0,"$38,676","$17,386",100%,85%,"$11,404",2%,"$12,759",21.0
5.0,Amherst College,MA,1618.0,18%,94.0,9.0,84%,94%,5.0,"$38,492","$14,453",100%,92%,"$33,411",NaN,"$11,544",38.0
6.0,Webb Institute,NY,67.0,42%,100.0,7.0,79%,83%,39.0,"$8,079","$5,579",20%,100%,"$8,079",100%,"$5,700",1.0
7.0,Yale University,CT,5339.0,8%,97.0,7.0,88%,95%,3.0,"$38,432","$15,729",100%,89%,"$38,432",NaN,"$19,228",53.0
8.0,Washington and Lee University,VA,1750.0,31%,89.0,11.0,86%,89%,30.0,"$30,225","$15,452",99%,87%,"$22,063",31%,"$15,634",9.0
9.0,Harvard University,MA,6637.0,11%,90.0,8.0,86%,97%,8.0,"$38,831","$17,456",100%,90%,"$33,201",NaN,"$10,465",46.0
10.0,Stanford University,CA,7360.0,13%,95.0,7.0,77%,93%,6.0,"$38,875","$17,746",100%,86%,"$33,709",NaN,"$15,782",62.0
11.0,Princeton University,NJ,4779.0,11%,97.0,5.0,91%,97%,7.0,"$40,169","$18,325",100%,94%,"$40,169",NaN,"$12,000",59.0
12.0,Massachusetts Institute of Technology,MA,4178.0,16%,100.0,6.0,82%,91%,2.0,"$39,213","$19,609",100%,85%,"$30,337",NaN,"$22,855",82.0
13.0,Pomona College,CA,1551.0,23%,98.0,9.0,83%,88%,21.0,"$38,130","$17,411",100%,80%,"$35,702",NaN,"$15,600",43.0
14.0,Emory University,GA,6302.0,42%,94.0,7.0,82%,87%,15.0,"$37,272","$19,657",100%,73%,"$23,615",19%,"$17,675",54.0
15.0,Columbia University,NY,4109.0,12%,93.0,7.0,83%,93%,13.0,"$39,493","$17,778",100%,86%,"$39,493",NaN,"$15,331",65.0
16.0,Duke University,NC,6206.0,25%,94.0,11.0,88%,93%,11.0,"$40,080","$19,996",100%,80%,"$26,599",6%,"$20,025",68.0
17.0,Davidson College,NC,1645.0,34%,89.0,10.0,89%,91%,27.0,"$34,706","$21,455",100%,82%,"$28,630",35%,"$13,697",37.0
18.0,Wellesley College,MA,2300.0,47%,89.0,9.0,84%,88%,32.0,"$37,419","$17,526",100%,88%,"$32,919",NaN,"$15,697",35.0
19.0,Vassar College,NY,2472.0,31%,93.0,9.0,81%,87%,22.0,"$37,870","$19,404",100%,78%,"$34,669",NaN,"$17,170",64.0
20.0,Haverford College,PA,1105.0,32%,90.0,8.0,89%,92%,20.0,"$38,928","$17,826",100%,90%,"$38,928",NaN,"$15,253",66.0
21.0,Northwestern University,IL,7946.0,33%,92.0,7.0,83%,92%,17.0,"$38,817","$20,376",100%,79%,"$36,538",12%,"$14,551",74.0
22.0,Bowdoin College,ME,1657.0,25%,92.0,10.0,83%,90%,25.0,"$38,663","$17,773",100%,85%,"$37,663",4%,"$15,307",58.0
23.0,University of Pennsylvania,PA,9742.0,21%,96.0,6.0,83%,91%,9.0,"$39,040","$20,596",100%,77%,"$39,040",NaN,"$20,247",93.0
24.0,Johns Hopkins University,MD,4112.0,35%,93.0,8.0,81%,88%,29.0,"$39,188","$19,142",95%,80%,"$24,206",9%,"$13,600",48.0
25.0,Cooper Union,NY,917.0,14%,83.0,7.0,57%,78%,61.0,"$14,652","$11,167",92%,62%,"$14,653",100%,"$9,250",3.0

### Question 3. From all cost based attributes, Remove $ sign and commas.

In [9]:

comma = ','
dollar = '$'


def clean_costs(item):
    set= str(item.loc['Total Costs'])
    
 
    if comma in set:
        comma_index = set.find(comma)
        set = set[:comma_index] + set[comma_index + 1:]
    
    return set

    if set == 'nan':
        return np.NaN
    
    set = set[1:]
   

data['Total Costs'] = data.apply(clean_costs, axis = 1)

In [10]:
# removing dollar($) from Cost According To given condtions

comma = ','
dollar = '$'


def clean_costs(item):
    set= str(item.loc['Cost After Need-based Aid'])
    
    if comma in set:
        comma_index = set.find(comma)
        set = set[:comma_index] + set[comma_index + 1:]
    
    return set    

    if set == 'nan':
        return np.NaN
    
    set = set[1:]
    


data['Cost After Need-based Aid'] = data.apply(clean_costs, axis = 1)

In [38]:
# removing dollar($) from Cost After Non-Need-based Aid' 

dollar = '$'
comma = ','

def clean_costs(item):
    set= str(item.loc['Cost After Non-Need-Based Aid'])
  
    if comma in set:
        comma_index = set.find(comma)
        set = set[:comma_index] + set[comma_index + 1:]
    
    return set

    if set == 'nan':
        return np.NaN
    
    set = set[1:]
    

data['Cost After Non-Need-Based Aid'] = data.apply(clean_costs, axis = 1)

In [11]:
# removing dollar($) from average debt' 

dollar = '$'
comma = ','

def clean_costs(item):
    set= str(item.loc['Average Debt'])
    
    if comma in set:
        comma_index = set.find(comma)
        set = set[:comma_index] + set[comma_index + 1:]
    
    return set    

    if set == 'nan':
        return np.NaN
    
    set = set[1:]
    


data['Average Debt'] = data.apply(clean_costs, axis = 1)

In [12]:
data.head()

,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Non-Need-Based Aid+,Average Debt,Cost Rank
Overall Rank,,,,,,,,,,,,,,,,,
1.0,California Institute of Technology,CA,939.0,21%,100.0,3.0,71%,85%,10.0,$32682,$10981,100%,93%,"$18,553",15%,$10244,4.0
2.0,Rice University,TX,2787.0,24%,92.0,5.0,68%,89%,19.0,$28350,$14779,100%,88%,"$22,418",34%,$12705,5.0
3.0,Williams College,MA,1985.0,23%,93.0,8.0,89%,94%,1.0,$36550,$14737,100%,89%,"$33,251",NaN,$12316,26.0
4.0,Swarthmore College,PA,1479.0,24%,98.0,8.0,86%,92%,4.0,$38676,$17386,100%,85%,"$11,404",2%,$12759,21.0
5.0,Amherst College,MA,1618.0,18%,94.0,9.0,84%,94%,5.0,$38492,$14453,100%,92%,"$33,411",NaN,$11544,38.0

### Question 4. remove  null value in  attribute.

In [15]:
data.dropna(how = 'all', inplace = True)
data.head()

,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Non-Need-Based Aid+,Average Debt,Cost Rank
Overall Rank,,,,,,,,,,,,,,,,,
1.0,California Institute of Technology,CA,939.0,21%,100.0,3.0,71%,85%,10.0,$32682,$10981,100%,93%,"$18,553",15%,$10244,4.0
2.0,Rice University,TX,2787.0,24%,92.0,5.0,68%,89%,19.0,$28350,$14779,100%,88%,"$22,418",34%,$12705,5.0
3.0,Williams College,MA,1985.0,23%,93.0,8.0,89%,94%,1.0,$36550,$14737,100%,89%,"$33,251",NaN,$12316,26.0
4.0,Swarthmore College,PA,1479.0,24%,98.0,8.0,86%,92%,4.0,$38676,$17386,100%,85%,"$11,404",2%,$12759,21.0
5.0,Amherst College,MA,1618.0,18%,94.0,9.0,84%,94%,5.0,$38492,$14453,100%,92%,"$33,411",NaN,$11544,38.0